services:
  whoami:
    image: "traefik/whoami"
    command: --name=iamfoo
    networks:
      - traefik_ingress
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.entrypoints=http
        - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
        - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  # Traefik Ingress Network
  traefik_ingress:
    external: true
