x-deploy: &x-deploy
  replicas: 1
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager

x-logging: &x-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  traefik:
    image: traefik:v2.11
    command:
      - --providers.file.watch=true
      - --providers.file.directory=/traefik.d
    environment:
      # ACME TLS Production
      - TRAEFIK_CERTIFICATESRESOLVERS_ACME_PRODUCTION_ACME_EMAIL
      - TRAEFIK_CERTIFICATESRESOLVERS_ACME_PRODUCTION_ACME_CASERVER
      # ACME TLS Production
      - TRAEFIK_CERTIFICATESRESOLVERS_ACME_STAGING_ACME_EMAIL
      - TRAEFIK_CERTIFICATESRESOLVERS_ACME_STAGING_ACME_CASERVER
    ports:
      # HTTP/HTTPS
      - mode: host
        target: 80
        published: 80
        protocol: tcp
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      # Traefik Dashboard
      - 8080:8080
    networks:
      - traefik_ingress
      - dockerswarm_sd_network
    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml
    volumes:
      - acme:/acme
    deploy: *x-deploy
    logging: *x-logging

configs:
  traefik.yml:
    file: configs/traefik.yml
    template_driver: golang

volumes:
  acme:

networks:
  traefik_ingress: # Traefik Ingress Network
    external: true
  dockerswarm_sd_network: # Docker Swarm Service Discovery
    external: true
