services:
  loadbalancer:
    configs:
    - source: haproxy.cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      mode: global
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: haproxy
        io.prometheus.scrape_port: "8405"
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        failure_action: continue
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 2m0s
    image: haproxy:3.0
    networks:
      prometheus: null
      traefik: null
    ports:
    - mode: host
      target: 80
      published: 80
      protocol: tcp
    - mode: host
      target: 443
      published: 443
      protocol: tcp
    - mode: host
      target: 443
      published: 443
      protocol: udp
    - mode: host
      target: 8080
      published: 8080
      protocol: tcp
    - mode: host
      target: 8404
      published: 8404
      protocol: tcp
    user: "0:0"
networks:
  prometheus:
    name: prometheus
    external: true
  traefik: {}
configs:
  haproxy.cfg:
    name: traefik-ingress-loadbalancer-config-v1
    file: ./configs/haproxy.cfg
