global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https
    #       scheme: https
  websecure:
    address: ":443"

providers:
  docker: # traefik < v3.0
    endpoint: "unix:///var/run/docker.sock"
    # endpoint: "tcp://127.0.0.1:2377"
    swarmMode: true
    exposedByDefault: false
    defaultRule: "Host(`{{ .Spec.Name }}`)"
  # swarm: # traefik >= v3.0
  #   endpoint: "unix:///var/run/docker.sock"
  #   # endpoint: "tcp://127.0.0.1:2377"
  #   exposedByDefault: false
  #   defaultRule: "Host(`{{ .Spec.Name }}`)"
